version: '3.7'

services:
    fsnb:
        image: fsnbimage
        container_name: fsnb
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
          - ".:/notebooks:rw"
        ports: 
          - "9091:8888"
        restart: always
        tty: true
        stdin_open: true
