services:
  fsnb:
    image: hkarhani/fsnb:latest
    container_name: fsnb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:8888"
    volumes:
      - ./:/notebooks:rw
    working_dir: /notebooks
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      JUPYTER_PORT: "8888"
      JUPYTER_IP: "0.0.0.0"
      JUPYTER_NOTEBOOK_DIR: "/notebooks"
      DOCKER_STACKS_JUPYTER_CMD: "lab"